steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/healthyeat-ml-api:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/healthyeat-ml-api:$COMMIT_SHA']
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   entrypoint: 'gcloud'
#   args: ['run', 'deploy', 'healthyeat-ml-api', '--image', 'gcr.io/$PROJECT_ID/healthyeat-ml-api:$COMMIT_SHA', '--region', 'asia-southeast2', '--platform', 'managed']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: [
    'run', 'deploy', 'healthyeat-ml-api', 
    '--image', 'gcr.io/$PROJECT_ID/healthyeat-ml-api:$COMMIT_SHA', 
    '--region', 'asia-southeast2', 
    '--platform', 'managed',
    '--memory', '1Gi',
    '--set-env-vars', 'MAX_MEMORY_LIMIT=1Gi',
    '--max-instances', '5'
  ]

images:
- 'gcr.io/$PROJECT_ID/healthyeat-ml-api:$COMMIT_SHA'

logsBucket: 'gs://model-ml-healthyeat/logs'
